# Generated by Django 5.1.6 on 2025-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcontent',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Reviewed', 'Reviewed'), ('Completed', 'Completed')], default='In progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentcontent',
            name='teacher',
            field=models.EmailField(max_length=254),
        ),
    ]
