# Generated by Django 5.1.6 on 2025-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_assessmentcontent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcontent',
            name='assess_text_file',
            field=models.FilePathField(blank=True, max_length=256, null=True, path='media/assessment_texts/'),
        ),
    ]
