# Generated by Django 5.1.6 on 2025-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assessmentcontent_assess_text_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcontent',
            name='feedback',
        ),
        migrations.AddField(
            model_name='assessmentcontent',
            name='summary_file',
            field=models.FilePathField(blank=True, max_length=256, null=True, path='media/summaries/'),
        ),
    ]
