# Generated by Django 5.1.6 on 2025-10-28 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_assessmentcontent_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcontent',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Submitted', 'Submitted'), ('Checked', 'Checked')], default='In progress', max_length=100),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('assigned_to', models.ManyToManyField(related_name='assignments_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_author', to=settings.AUTH_USER_MODEL)),
                ('evaluators', models.ManyToManyField(related_name='assignments_evaluators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentcontent',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='app.assignment'),
        ),
    ]
