# Generated by Django 5.1.6 on 2025-10-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_assessmentcontent_status_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcontent',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='app.assignment'),
        ),
    ]
