# Generated by Django 5.1.6 on 2025-10-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_assessmentcontent_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcontent',
            name='teacher',
        ),
    ]
