# Generated by Django 5.1.6 on 2025-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assessmentcontent_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcontent',
            name='teacher_feedback_file',
            field=models.FilePathField(blank=True, max_length=1280, null=True, path='media/teacher_feedbacks/'),
        ),
    ]
